version: "3.8"

services:
  lambda:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-dummy-key}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-dummy-secret}
      - AWS_REGION=${AWS_REGION:-ap-northeast-1}
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/data"]
    volumes:
      - dynamodb-data:/data

volumes:
  dynamodb-data:
